<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    public function getTopFilms($max)
    {
        return $this
            ->createQueryBuilder('f')
            ->setMaxResults($max)
            ->getQuery()
            ->getResult()
        ;
    }
}
